name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  call-workflow:
    uses: craftcms/.github/.github/workflows/ci.yml@v1
    with:
      run_ecs: true
      run_phpstan: true
      run_tests: true
      php_versions: '[7.2]'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_PLUGIN_WEBHOOK_URL }}
